auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Long Teng
url: http://longtengz.github.io
feed: /atom.xml
author_info: <a href="http://longtengz.github.io/">Long Teng</a>


gaaccount: 'UA-40460783-2'
